name: Code Quality Checks

on:
  push:


jobs:
  condig-standards:
    name: "Coding Standards"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php-version:
          - "8.3"

        dependencies:
          - "locked"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: phpunit-bridge
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pgsql
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: 'backend/vendor'
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        working-directory: backend
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: PHP Code Sniffer
        working-directory: backend
        run: |
          php vendor/bin/phpcs

      - name: PHPStan Static Analysis
        working-directory: backend
        run: |
          php vendor/bin/phpstan